
name: CI Java

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Descarga Codigo
        run: ls -ltr

      - name: Setup del JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build realizado con Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean :service-a:build
