name: CI Java

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Descarga Codigo
        run: ls -ltr

      - name: Build Gradle
        uses: gradle/gradle-build-action@2.7.0
