name: Pipeline Tarea Final Julio Tabilo
on:
  push:
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '11'
          distribution: 'temurin' 
          
     # - name: Cache SonarCloud packages
     #   uses: actions/cache@v3
      #  with:
      #    path: ~/.sonar/cache
       #  key: ${{ runner.os }}-sonar
        #  restore-keys: ${{ runner.os }}-sonar
          
      #- name: Cache Gradle packages
       # uses: actions/cache@v3
        #with:
         # path: ~/.gradle/caches
          #key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          #restore-keys: ${{ runner.os }}-gradle 
          
      - name: Build 
        run: |
          chmod +x gradlew
          ./gradlew clean build bootBuildImage

      - name: Verificar creacion compilado JAR
        run: |
            ls -lt 
            ls -lt $GITHUB_WORKSPACE/build
            ls -lt $GITHUB_WORKSPACE/service-a/build/libs
            ls -lt $GITHUB_WORKSPACE/service-b/build/libs
            ls -lt $GITHUB_WORKSPACE/service-c/build/libs

      - name: Carga JAR's
        run: |
          java -jar $GITHUB_WORKSPACE/service-a/build/libs/service-a-0.0.1-SNAPSHOT.jar &
          java -jar $GITHUB_WORKSPACE/service-b/build/libs/service-b-0.0.1-SNAPSHOT.jar &
          java -jar $GITHUB_WORKSPACE/service-c/build/libs/service-c-0.0.1-SNAPSHOT.jar &

      - name: Wait / Sleep
        # You may pin to the exact commit or the version.
        # uses: jakejarvis/wait-action@919fc193e07906705e5b7a50f90ea9e74d20b2b0
        uses: jakejarvis/wait-action@v0.1.1
        with:
          # Follows the Linux sleep syntax for time units: a number followed by s for seconds, m for minutes, etc
          time: 5s

      
        run: |
          curl 127.0.0.1:8081/greeting || true
          curl 127.0.0.1:8082/greeting || true
          curl 127.0.0.1:8083/greeting || true

      - name: Apache JMeter
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: 'tarea.jmx'
      - name: Prueba JAR's compilados
        uses: matt-ball/newman-action@master
        with:
          collection: Demo-My.postman_collection.json


     
     # - name: Docker Login
     #  uses: docker/login-action@v2.2.0
     #   with:
     #     username: ${{ secrets.DOCKER_USERNAME }} 
     #     password: ${{ secrets.DOCKER_PASSWORD }} 

      #- name: Docker Build
       # run: |
        #  docker images | grep spring-multi-module
        #  docker tag 7d820823f33c jtabilo0811/springboot-servicea
        #  docker tag c46339799598 jtabilo0811/springboot-serviceb
        #  docker tag 61e555bbcb7b jtabilo0811/springboot-servicec

        #  docker push jtabilo0811/springboot-servicea
        #  docker push jtabilo0811/springboot-serviceb
        #  docker push jtabilo0811/springboot-servicec 

        #  docker run -d -p 8081:8080 -e spring.profiles.active=prod -e serviceb.url=http://localhost:8082 -e servicec.url=http://localhost:8083 jtabilo0811/springboot-servicea:latest
        #  docker run -d -p 8082:8080 -e spring.profiles.active=prod jtabilo0811/springboot-serviceb:latest
        #  docker run -d -p 8083:8080 -e spring.profiles.active=prod jtabilo0811/springboot-servicec:latest
          
        # docker ps -a
      

              
